using LiteQueue;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;
using Testcontainers.PostgreSql;
using Xunit;

namespace LiteFlow.Tests;

/// <summary>
/// One throwaway PostgreSQL container shared by the whole test run. Tests isolate themselves with fresh
/// workflow ids and unique definition names rather than by resetting the database, so they can run
/// against the same container without interfering — and so the assertions look at exactly the rows the
/// test produced.
/// </summary>
public sealed class PostgresFixture : IAsyncLifetime
{
    private readonly PostgreSqlContainer _container = new PostgreSqlBuilder("postgres:18-alpine")
        .Build();

    /// <summary>Connection string every provider in the run is built on.</summary>
    public string ConnectionString { get; private set; } = string.Empty;

    public async Task InitializeAsync()
    {
        await _container.StartAsync();

        // Host=localhost resolves to ::1 first on this platform and the container only listens on the
        // IPv4 loopback, so the first connection attempt is refused. Pin the address.
        var builder = new NpgsqlConnectionStringBuilder(_container.GetConnectionString())
        {
            Host = "127.0.0.1",
            // Every provider a test builds gets its own side-channel pool; bound them so a run with
            // several providers alive cannot exhaust the server's connection slots.
            MaxPoolSize = 8,
        };
        ConnectionString = builder.ConnectionString;

        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText =
            """
            -- The caller's own schema: what the transactional tests write to.
            CREATE TABLE IF NOT EXISTS public.business_records (
                id    bigint PRIMARY KEY,
                value text NOT NULL
            );

            -- One row per step execution that actually committed. No unique constraint on purpose: a
            -- double execution has to show up as two rows, not as an error the engine could swallow.
            CREATE TABLE IF NOT EXISTS public.step_executions (
                seq         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                workflow_id uuid NOT NULL,
                step_name   text NOT NULL,
                attempt     integer NOT NULL,
                recorded_at timestamptz NOT NULL DEFAULT now()
            );

            -- Same, for compensations: the insertion order is what proves they ran in reverse.
            CREATE TABLE IF NOT EXISTS public.step_compensations (
                seq         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                workflow_id uuid NOT NULL,
                step_name   text NOT NULL,
                recorded_at timestamptz NOT NULL DEFAULT now()
            );
            """;
        await command.ExecuteNonQueryAsync();

        // Create both schemas once up front so individual tests never race on the DDL.
        await using var provider = BuildProvider(_ => { });
        await using var scope = provider.CreateAsyncScope();
        await scope.ServiceProvider.GetRequiredService<ILiteFlowClient>().InitializeAsync();
    }

    public async Task DisposeAsync() => await _container.DisposeAsync();

    /// <summary>
    /// A container wired the way an application would be: LiteFlow rides on
    /// <see cref="TestDbContext"/>'s connection, so a step's writes and the cursor advance share a
    /// transaction.
    /// </summary>
    /// <param name="register">Registers the workflows (and workers) this provider hosts.</param>
    /// <param name="configure">Overrides on top of the test defaults.</param>
    public ServiceProvider BuildProvider(
        Action<IServiceCollection> register,
        Action<LiteFlowOptions>? configure = null)
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddSingleton<StepScript>();
        services.AddSingleton(new TestDatabase(ConnectionString));
        services.AddDbContext<TestDbContext>(o => o.UseNpgsql(ConnectionString));

        services.AddLiteFlow<TestDbContext>(o =>
        {
            o.ConnectionString = ConnectionString;
            // Tests must not wait on production-sized timers.
            o.MaintenanceInterval = TimeSpan.FromSeconds(1);
            o.CancellationPollInterval = TimeSpan.FromMilliseconds(300);
            o.OrphanGracePeriod = TimeSpan.FromSeconds(30);
            o.StepRetry = new RetryBackoff
            {
                BaseDelay = TimeSpan.FromMilliseconds(100),
                Factor = 1,
                MaxDelay = TimeSpan.FromMilliseconds(200),
                Jitter = 0,
            };
            // Polling at 100 ms is fast enough here, and one LISTEN connection per provider is not worth
            // it in a run that builds dozens of them.
            o.EnableNotifications = false;
            configure?.Invoke(o);
        });

        register(services);
        return services.BuildServiceProvider();
    }

    /// <summary>A definition name nothing else in the run uses.</summary>
    public static string NewName(string prefix) => $"{prefix}-{Guid.NewGuid():N}";
}

/// <summary>Handle on the test database for the assertions that look past the public API.</summary>
public sealed class TestDatabase(string connectionString)
{
    public string ConnectionString { get; } = connectionString;
}

[CollectionDefinition("postgres")]
public sealed class PostgresCollection : ICollectionFixture<PostgresFixture>;
